[config]
default_to_workspace = false

[tasks.format]
command = "echo"
args = ["Formatting complete"]
dependencies = [
  { name = "format", path = "server/tasks.toml" },
  { name = "format", path = "viewer/tasks.toml" },
]

[tasks.clean]
dependencies = ["clean-server", "clean-viewer", "clean-mcp"]

[tasks.clean-server]
command = "cargo"
args = ["make", "--cwd", "server", "--makefile", "tasks.toml", "clean"]

[tasks.clean-viewer]
command = "cargo"
args = ["make", "--cwd", "viewer", "--makefile", "tasks.toml", "clean"]

[tasks.clean-mcp]
command = "cargo"
args = ["clean"]
cwd = "mcp"

[tasks.build]
dependencies = ["build-server", "build-viewer", "build-mcp"]

[tasks.build-server]
command = "cargo"
args = ["make", "--cwd", "server", "--makefile", "tasks.toml", "build"]

[tasks.build-viewer]
command = "cargo"
args = ["make", "--cwd", "viewer", "--makefile", "tasks.toml", "build"]

[tasks.build-mcp]
command = "cargo"
args = ["build", "--release"]
cwd = "mcp"

[tasks.test]
dependencies = ["test-server", "test-viewer"]

[tasks.test-server]
command = "cargo"
args = ["make", "--cwd", "server", "--makefile", "tasks.toml", "test"]

[tasks.test-viewer]
command = "cargo"
args = ["make", "--cwd", "viewer", "--makefile", "tasks.toml", "test"]

[tasks.full-build]
dependencies = [
    "format",
    "build",
    "test"
]

[tasks.run-server]
command = "cargo"
args = ["make", "--cwd", "server", "--makefile", "tasks.toml", "run"]

[tasks.run-viewer]
command = "cargo"
args = ["make", "--cwd", "viewer", "--makefile", "tasks.toml", "run"]

[tasks.run-mcp]
command = "cargo"
args = ["run"]
cwd = "mcp"

[tasks.watch-server]
dependencies = [
  { name = "watch", path = "server/tasks.toml" },
]

[tasks.watch-viewer]
dependencies = [
  { name = "watch", path = "viewer/tasks.toml" },
]