[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = { version = "3.1.11", features = ["sse"] }
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["full"] }
futures-util = "0.3.31"
tokio-stream = "0.1.17"
tracing-subscriber = "0.3.19"