[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = { version = "3.1", features = ["sse"] }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.45", features = ["full"] }
futures-util = "0.3"
tokio-stream = "0.1"
tracing-subscriber = "0.3"